[project]
name = "pytest-action tests"
version = "0.1.0"
description = "Add a short description here"
authors = []
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]

[dependencies]
python = "*"
pytest = "*"
pytest-md = "*"
pytest-emoji = "*"
